// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package manager

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/manager/job/all": {
            "get": {
                "description": "This method will return a list of all jobs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "lists all jobs",
                "operationId": "job-list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.JobListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/manager.FailureResponse"
                        }
                    }
                }
            }
        },
        "/manager/job/details/{job_id}": {
            "get": {
                "description": "This method will return a single job by it's id or an error.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "find a single job by it's id and shows all fields",
                "operationId": "job-details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.JobDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/manager.FailureResponse"
                        }
                    }
                }
            }
        },
        "/manager/pipeline/": {
            "post": {
                "description": "This method will create the pipeline sent via the post body",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "creates a pipeline",
                "operationId": "pipeline-create",
                "parameters": [
                    {
                        "description": "Pipeline Script",
                        "name": "pipeline",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.PipelineCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/manager.FailureResponse"
                        }
                    }
                }
            }
        },
        "/manager/pipeline/all": {
            "get": {
                "description": "This method will return a list of all registered pipelines",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "lists all registered pipelines",
                "operationId": "pipeline-list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.PipelineListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/manager.FailureResponse"
                        }
                    }
                }
            }
        },
        "/manager/pipeline/details/{pipeline_id}": {
            "get": {
                "description": "This method will return a single pipeline by it's id or an error.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "find a pipeline by it's id and shows all fields",
                "operationId": "pipeline-details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipeline_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.PipelineDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/manager.FailureResponse"
                        }
                    }
                }
            }
        },
        "/manager/pipeline/execute/{pipeline_id}": {
            "post": {
                "description": "This method will execute the pipeline with the given id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "executes a pipeline",
                "operationId": "pipeline-execute",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipeline_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Body",
                        "name": "execute_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manager.PipelineExecuteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/manager.FailureResponse"
                        }
                    }
                }
            }
        },
        "/manager/pipeline/{pipeline_id}": {
            "delete": {
                "description": "This method will delete the given pipeline",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "deletes the pipeline with the given id",
                "operationId": "pipeline-delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipeline_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/manager.FailureResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "This method will update the given pipeline from a provided script",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "updates the pipeline with the given id",
                "operationId": "pipeline-update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID",
                        "name": "pipeline_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pipeline Script",
                        "name": "pipeline",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.PipelineDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/manager.FailureResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "manager.FailureResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "manager.JobDetailsResponse": {
            "type": "object",
            "properties": {
                "job": {
                    "type": "object",
                    "$ref": "#/definitions/model.Job"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/messages.Message"
                    }
                }
            }
        },
        "manager.JobListResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Job"
                    }
                }
            }
        },
        "manager.PipelineCreateResponse": {
            "type": "object",
            "properties": {
                "pipeline": {
                    "type": "object",
                    "$ref": "#/definitions/model.Pipeline"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "manager.PipelineDetailsResponse": {
            "type": "object",
            "properties": {
                "pipeline": {
                    "type": "object",
                    "$ref": "#/definitions/model.Pipeline"
                }
            }
        },
        "manager.PipelineExecuteRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.JobParameter"
                    }
                }
            }
        },
        "manager.PipelineListResponse": {
            "type": "object",
            "properties": {
                "pipelines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Pipeline"
                    }
                }
            }
        },
        "manager.SuccessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "messages.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "model.Job": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.JobParameter"
                    }
                },
                "pipeline": {
                    "type": "object",
                    "$ref": "#/definitions/model.Pipeline"
                }
            }
        },
        "model.JobParameter": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "model.Pipeline": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "pipeline": {
                    "type": "object",
                    "$ref": "#/definitions/pipeline.Pipeline"
                },
                "revision": {
                    "type": "integer"
                },
                "script": {
                    "type": "string"
                }
            }
        },
        "pipeline.Command": {
            "type": "object",
            "properties": {
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "pipeline.Expression": {
            "type": "object",
            "properties": {
                "script": {
                    "type": "string"
                }
            }
        },
        "pipeline.Parameter": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "pipeline.Pipeline": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipeline.Parameter"
                    }
                },
                "stages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipeline.Stage"
                    }
                }
            }
        },
        "pipeline.Stage": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipeline.Task"
                    }
                }
            }
        },
        "pipeline.Task": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipeline.Command"
                    }
                },
                "ignore_errors": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "notify": {
                    "description": "NotifyRef",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "register": {
                    "description": "VariableRef",
                    "type": "string"
                },
                "when": {
                    "type": "object",
                    "$ref": "#/definitions/pipeline.Expression"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "dips",
	Description: "dips manager api",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
