version: "3.5"

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672

  mongodb:
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "mongodb"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "mongodb"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
    networks:
      - mongodb

  influxdb:
    ports:
      - 8086:8086

  chronograf:
    image: chronograf:1.8
    ports:
      - 8888:8888
    command: chronograf --influxdb-url=http://influxdb:8086
    networks:
      - influx

  minio:
    ports:
      - 9000:9000
