version: "3.5"

services:

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - rabbitmq

  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongodb"
      MONGO_INITDB_ROOT_PASSWORD: "mongodb"
      MONGO_INITDB_DATABASE: "dips"
    volumes:
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    networks:
      - mongodb

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "miniominio"
    volumes:
      - minio-data:/data
    command: server /data/minio
    networks:
      - minio

networks:
  rabbitmq: {}
  mongodb: {}
  minio: {}

volumes:
  minio-data:
