[mongodb]
hosts=["localhost"]
database="dips"
username="dips"
password="dips"

[influxdb]
host="http://localhost:8086"
database="dips"
username="dips"
password="dips"

[amqp]
host="rabbitmq:rabbitmq@localhost"