[amqp]
host="rabbitmq:rabbitmq@localhost"

[mongodb]
hosts=["mongodb://localhost:27017"]
auth_mechanism="SCRAM-SHA-256"
auth_source="dips"
username="dips"
password="dips"
database="dips"

[influxdb]
host="http://localhost:8086"
database="dips"
username="dips"
password="dips"
